name: Notify Diag (manual ping)

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "notify pipeline alive: ${{ github.repository }} / ${{ github.ref }}"


